In [1]:
import numpy as np

In [2]:
a = [2, 5, 7]

In [3]:
b = [3, 12, 27]

In [4]:
a+b

[2, 5, 7, 3, 12, 27]

In [5]:
c = [m+n for m, n in zip(a,b)]

In [6]:
c

[5, 17, 34]

In [7]:
sum(a)

14

In [8]:
np_a = np.array(a)

In [9]:
np_b = np.array(b)

In [10]:
np_a + np_b

array([ 5, 17, 34])

In [11]:
p = np.array([1,2,"abc"])

In [12]:
p

array(['1', '2', 'abc'], dtype='<U11')

In [13]:
p+ np_a

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('int32')) -> None

In [14]:
np_a.max()

7

In [15]:
np_a.mean()

4.666666666666667

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np_a*np.ones(3)

array([2., 5., 7.])

In [19]:
np_a*[3]

array([ 6, 15, 21])

In [20]:
np_a*np.array([2.2])

array([ 4.4, 11. , 15.4])

In [21]:
np_a*np.array([2.2,3.2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [22]:
np_a[1]

5

In [23]:
np_a[1:]

array([5, 7])

In [24]:
np_a[0:2]

array([2, 5])

In [25]:
np_2d = np.array([[1,2],[3,4]])

In [26]:
np_2d.sum()

10

In [27]:
np_2d.sum(axis=0)

array([4, 6])

In [28]:
np_2d.sum(axis=1)

array([3, 7])

In [29]:
np_2d.T()

TypeError: 'numpy.ndarray' object is not callable

In [30]:
np_2d.T

array([[1, 3],
       [2, 4]])

In [31]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [32]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [33]:
np_2d

array([[1, 2],
       [3, 4]])

In [34]:
np_2d+np.ones([2,2])

array([[2., 3.],
       [4., 5.]])

In [35]:
np_2d+np.ones(2)

array([[2., 3.],
       [4., 5.]])

In [36]:
np_2d+np.ones([2,1])

array([[2., 3.],
       [4., 5.]])

In [37]:
np_dotp = np_2d.dot(np.array([[1,10,100],[1000,100,10]]))

In [38]:
np_dotp

array([[2001,  210,  120],
       [4003,  430,  340]])

In [39]:
np_dotp[0,1]

210

In [40]:
np_dotp[1:3]

array([[4003,  430,  340]])

In [41]:
np_dotp[0:2,0]

array([2001, 4003])

In [42]:
np_rs = np.array([1,2,3,4,5,6])

In [43]:
np_rs

array([1, 2, 3, 4, 5, 6])

In [44]:
np_rs.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np_rs.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
np_rs.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
np_rs.reshape(4,-1)

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

In [48]:
np_rs.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np_rs.reshape(2,2,-1)

ValueError: cannot reshape array of size 6 into shape (2,2,newaxis)

In [50]:
np_rs.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.random(2)

TypeError: 'module' object is not callable

In [52]:
np.random.random(2)

array([0.82511608, 0.55497121])

In [53]:
import np.random as random

ModuleNotFoundError: No module named 'np'

In [54]:
import numpy.random as random

In [55]:
random(2)

TypeError: 'module' object is not callable

In [56]:
random.random(2)

array([0.50331931, 0.1988937 ])

In [57]:
random.random([3,2])

array([[0.97847756, 0.47523392],
       [0.09653067, 0.40917114],
       [0.44878372, 0.03724573]])

In [58]:
import numpy.linalg as la

In [59]:
la.inv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [60]:
la.eig(np_2d)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [61]:
la.svd(np_2d)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

In [62]:
la.pinv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [63]:
random.rand(2,3)*5

array([[1.5157604 , 2.37875162, 2.0047976 ],
       [2.77593434, 0.44115862, 2.52998529]])

In [64]:
random.randn(2,3)

array([[-0.5031623 , -0.11486942,  0.24696024],
       [ 0.76810465, -0.40332098,  0.34895206]])

In [65]:
random.randint(-2,3,5)

array([-2,  2,  0,  2, -1])

In [66]:
random.shuffle(np_rs)

In [67]:
np_rs

array([6, 3, 2, 1, 4, 5])

In [68]:
random.choice(np_rs, 2)

array([1, 5])

In [69]:
random.binomial(20,0.3)

8

In [70]:
random.binomial(20, 0.3, 7)

array([4, 3, 4, 2, 6, 4, 6])

In [71]:
random.exponential(0.7,4)

array([1.62495145, 0.56979472, 0.10891431, 0.15254924])

In [ ]:
%%time


In [72]:
random.normal(-5,12,3)

array([14.75890713,  8.54274887, -6.39011871])

In [73]:
random.logistic(-2,4,7)

array([ 3.98827915, -5.55833392, -3.40702308,  1.02229681, -3.0953516 ,
       -1.51871937,  3.85298528])

In [74]:
np_2d.shape

(2, 2)

In [75]:
np_2d.dtype

dtype('int32')

In [76]:
type(np_2d)

numpy.ndarray

In [77]:
np.vstack(np.ones([2,2]))

array([[1., 1.],
       [1., 1.]])

In [78]:
np.vstack((np_2d,np.ones([2,2])))

array([[1., 2.],
       [3., 4.],
       [1., 1.],
       [1., 1.]])

In [79]:
np.hstack((np_2d,np.ones([2,2])))

array([[1., 2., 1., 1.],
       [3., 4., 1., 1.]])

In [80]:
N=10000000
x=list(range(N))
y=list(range(N)) 
z=[]

In [81]:
np_x = np.array(x)
np_y = np.array(y)

In [82]:
%%time
for i in range(len(x)):
    z.append(x[i]+y[i])


CPU times: total: 2.25 s
Wall time: 2.41 s


In [83]:
%%time
np_z = np_x+np_y

CPU times: total: 31.2 ms
Wall time: 23.8 ms


**Newton Method**
Perform this matrix computation -> ((X'X)^-1)*X'y, use only X and y values from rows 2 to 41
Error Computation (both Training and Test Error)

Generate y values from the new generated w values

Compute the SSR, MSR and RMSE between the generated y values and the actual values both for the data from rows 2 to 41 and the data from rows 43 to 51

**Regularized Newton**
Next step perform the matrix computation -> ((X'X+lambda*I)^-1)*X'y, using only X and y values from rows 2 to 41

**Use lambda as 0.17**
Compute and report both training and test errors for the regularized newton computation
Compute R-squared values for both Newton and Regularized Newton on both train and test datasets

Look up how to compute R-squared values in excel

Let's try some more things

For each of the below report the following, MSR on train, MSR on test, R-squared on train and R-squared on test
1. Use only rows 2 to 41 for training and rows 42 to 51 for testing and lambda as 0.83
2. Use only rows 2 to 26 for training and rows 27 to 51 for testing and lambda as 0.17
3. Use only rows 2 to 26 for training and rows 27 to 51 for testing and lambda as 0.83
4. Use only rows 2 to 11 for training and rows 12 to 51 for testing and lambda as 0.17
5. Use only rows 2 to 11 for training and rows 12 to 51 for testing and lambda as 0.83


In [84]:
# importing modules
import numpy as np
import pandas as pd

In [85]:
# accessing the data
np_df = pd.read_csv("NumpyExerciseData.csv")
np_df.head()

X0     X1     X2  X3  X4   X5   y  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0   1  5.768  62.55   0  28  2.6  28         NaN         NaN         NaN   
1   1  8.949  66.91   0  27 -2.0  46         NaN         NaN         NaN   
2   1  1.024  34.42   0  20 -3.4  14         NaN         NaN         NaN   
3   1  4.534  47.93   0  10  1.1  17         NaN         NaN         NaN   
4   1  8.641  35.26   0  30  3.8  32         NaN         NaN         NaN   

   Unnamed: 10  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN

In [86]:
# removing unwanted columns
np_df = np_df.drop(columns=["Unnamed: 7", "Unnamed: 8", "Unnamed: 9", "Unnamed: 10"])
np_df.head()

X0     X1     X2  X3  X4   X5   y
0   1  5.768  62.55   0  28  2.6  28
1   1  8.949  66.91   0  27 -2.0  46
2   1  1.024  34.42   0  20 -3.4  14
3   1  4.534  47.93   0  10  1.1  17
4   1  8.641  35.26   0  30  3.8  32

### Newton Method

**Training Error Computation**

In [87]:
# getting X_train and y_train values from rows 2 to 41 in matrices
X_train = np_df.iloc[1:41, :6].values
y_train = np_df.iloc[1:41, -1].values

In [88]:
X_train.shape

(40, 6)

In [89]:
y_train.shape

(40,)

In [90]:
# adding a column of ones to X_train
X_train = np.hstack((np.ones((X_train.shape[0], 1)), X_train))
X_train

array([[ 1.   ,  1.   ,  8.949, 66.91 ,  0.   , 27.   , -2.   ],
       [ 1.   ,  1.   ,  1.024, 34.42 ,  0.   , 20.   , -3.4  ],
       [ 1.   ,  1.   ,  4.534, 47.93 ,  0.   , 10.   ,  1.1  ],
       [ 1.   ,  1.   ,  8.641, 35.26 ,  0.   , 30.   ,  3.8  ],
       [ 1.   ,  1.   ,  1.063, 42.14 ,  0.   ,  6.   , -2.1  ],
       [ 1.   ,  1.   ,  5.306, 39.8  ,  0.   , 29.   , -1.8  ],
       [ 1.   ,  1.   ,  4.309, 36.14 ,  0.   , 12.   , -3.4  ],
       [ 1.   ,  1.   ,  3.739, 44.53 ,  0.   , 39.   ,  1.9  ],
       [ 1.   ,  1.   ,  3.816, 60.01 ,  0.   , 10.   , -3.4  ],
       [ 1.   ,  1.   ,  8.539, 36.9  ,  0.   , 31.   , -3.   ],
       [ 1.   ,  1.   ,  7.129, 35.77 ,  0.   , 38.   ,  3.5  ],
       [ 1.   ,  1.   ,  4.249, 37.17 ,  0.   , 23.   ,  0.8  ],
       [ 1.   ,  1.   , -2.99 , 42.41 ,  0.   , 20.   , -3.1  ],
       [ 1.   ,  1.   ,  0.356, 57.67 ,  0.   , 26.   , -3.8  ],
       [ 1.   ,  1.   ,  5.487, 35.25 ,  0.   , 10.   , -2.8  ],
       [ 1.   ,  1.   ,  

In [91]:
# computing the pseudo-inverse of (X^T*X)
X_tran_pinv_X = np.linalg.pinv(np.dot(X_train.T, X_train))
X_tran_pinv_X

array([[ 1.79223696e-01,  1.79223696e-01, -7.70448957e-03,
        -5.51191669e-03, -6.03476345e-02, -1.31260569e-03,
         7.08364373e-03],
       [ 1.79223696e-01,  1.79223696e-01, -7.70448957e-03,
        -5.51191669e-03, -6.03476345e-02, -1.31260569e-03,
         7.08364373e-03],
       [-7.70448957e-03, -7.70448957e-03,  3.74383963e-03,
        -1.43240965e-04,  4.85835606e-03,  1.53264469e-04,
        -1.63683045e-03],
       [-5.51191669e-03, -5.51191669e-03, -1.43240965e-04,
         2.69855722e-04,  1.30388694e-03, -4.84086991e-05,
         1.75956809e-04],
       [-6.03476345e-02, -6.03476345e-02,  4.85835606e-03,
         1.30388694e-03,  1.88171717e-01,  1.38157785e-04,
        -1.46562315e-03],
       [-1.31260569e-03, -1.31260569e-03,  1.53264469e-04,
        -4.84086991e-05,  1.38157785e-04,  1.46161890e-04,
        -4.51876741e-04],
       [ 7.08364373e-03,  7.08364373e-03, -1.63683045e-03,
         1.75956809e-04, -1.46562315e-03, -4.51876741e-04,
         5.4789660

In [92]:
# computing the weights
weight = np.dot(np.dot(X_tran_pinv_X, X_train.T), y_train)
weight

array([-3.91598187, -3.91598187,  3.26458338,  0.16631204, 12.19246692,
        0.38231333, -1.58835343])

In [93]:
# generating y values from the new generated w values
y_pred_train = np.dot(X_train, weight)
y_pred_train

array([46.00989848, 14.28209844, 17.016938  , 31.67512079,  8.27610001,
       30.05525777, 22.23380488, 23.67253722, 23.82960703, 42.7980017 ,
       30.35890257, 19.74359354,  2.03038794, 18.89733308, 24.21382766,
       22.2672154 , 22.40632288, 24.40462873, 23.33061978, 33.65574554,
       19.07939298, 46.29102151, 25.82780273, 28.29453625, 27.99148376,
       32.64119327, 27.55296899, 22.38771132, 32.9922996 , 28.17596851,
       19.68407044, 25.07237092, 27.80514037, 31.44189406, 33.13068768,
       41.02371652, 32.24130577, 33.03929752, 36.12821698, 58.04097939])

**Computing the training predictions**

In [94]:
SSR_train = np.sum((y_train - y_pred_train) ** 2)
MSR_train = SSR_train / (len(y_train))
RMSE_train = np.sqrt(MSR_train)

In [95]:
print("Training SSR:", SSR_train)

Training SSR: 2.9056340032037906


In [96]:
print("Training MSR_train:", MSR_train)

Training MSR_train: 0.07264085008009477


In [97]:
print("Training RMSE_train:", RMSE_train)

Training RMSE_train: 0.2695196654793389


**Test Error Computation**

In [98]:
# getting X_test and y_test values from rows 43 to 50 in matrices
X_test = np_df.iloc[42:51, :6]
y_test = np_df.iloc[42:51, -1]

In [99]:
X_test.shape

(8, 6)

In [100]:
y_test.shape

(8,)

In [101]:
# adding a column of ones to X_train
X_test = np.hstack((np.ones((X_test.shape[0], 1)), X_test))
X_test

array([[ 1.   ,  1.   ,  4.545, 39.25 ,  1.   , 18.   ,  2.2  ],
       [ 1.   ,  1.   ,  3.121, 36.89 ,  0.   , 20.   ,  4.1  ],
       [ 1.   ,  1.   ,  4.698, 40.65 ,  0.   ,  8.   , -1.8  ],
       [ 1.   ,  1.   , -0.328, 49.64 ,  0.   , 18.   ,  0.5  ],
       [ 1.   ,  1.   ,  5.216, 44.49 ,  1.   , 11.   ,  3.2  ],
       [ 1.   ,  1.   , -2.111, 51.31 ,  0.   , 25.   ,  2.6  ],
       [ 1.   ,  1.   ,  6.804, 36.12 ,  0.   , 24.   ,  3.   ],
       [ 1.   ,  1.   ,  5.643, 39.06 ,  0.   , 35.   , -1.9  ]])

In [102]:
# computing the pseudo-inverse of (X^T*X)
X_tran_pinv_X1 = np.linalg.pinv(np.dot(X_test.T, X_test))
X_tran_pinv_X1

array([[ 1.51486724e+01,  1.51486724e+01, -1.09976635e+00,
        -6.03206809e-01,  2.07463334e+00, -4.68405947e-02,
        -3.95966899e-01],
       [ 1.51486724e+01,  1.51486724e+01, -1.09976635e+00,
        -6.03206809e-01,  2.07463334e+00, -4.68405947e-02,
        -3.95966899e-01],
       [-1.09976635e+00, -1.09976635e+00,  9.57534797e-02,
         4.39348136e-02, -2.10745902e-01,  1.01292220e-03,
         3.28576799e-02],
       [-6.03206809e-01, -6.03206809e-01,  4.39348136e-02,
         2.45960881e-02, -9.21008368e-02,  8.97635839e-04,
         1.52728405e-02],
       [ 2.07463334e+00,  2.07463334e+00, -2.10745902e-01,
        -9.21008368e-02,  1.34061316e+00,  1.55378932e-02,
        -1.22359952e-01],
       [-4.68405947e-02, -4.68405947e-02,  1.01292220e-03,
         8.97635839e-04,  1.55378932e-02,  2.42484659e-03,
         1.68681986e-04],
       [-3.95966899e-01, -3.95966899e-01,  3.28576799e-02,
         1.52728405e-02, -1.22359952e-01,  1.68681986e-04,
         4.1485970

In [103]:
# computing the weights
weight1 = np.dot(np.dot(X_tran_pinv_X1, X_test.T), y_test)
weight1

array([-4.22337995, -4.22337995,  3.30122301,  0.17615777, 11.99000893,
        0.39546987, -1.57959521])

In [104]:
# generating y values from the new generated w values
y_pred_test = np.dot(X_test, weight1)
y_pred_test

array([29.10484845,  9.78787445, 20.23022966,  5.54357092, 27.89515155,
       -0.59718708, 25.13007152, 33.90544053])

**Computing test predictions**

In [105]:
SSR_test = np.sum((y_test - y_pred_test) ** 2)
MSR_test = SSR_test / (len(y_test))
RMSE_test = np.sqrt(MSR_test)

In [106]:
print("Test SSR:", SSR_test)

Test SSR: 0.5164351933231227


In [107]:
print("Test MSR_test:", MSR_test)

Test MSR_test: 0.06455439916539034


In [108]:
print("Test RMSE_test:", RMSE_test)

Test RMSE_test: 0.25407557766418704


### Regularized Newton method computation with λ = 0.17

**Regularized Newton Method - Training Computation**

In [109]:
# declaring lambda as 0.17
lambda_reg = 0.17

In [110]:
# computing the pseudo-inverse of (X'X+lambda*I)^-1)
X_tran_reg_pinv_X = np.linalg.pinv(np.dot(X_train.T, X_train) + lambda_reg * np.eye(X_train.shape[1]))
X_tran_reg_pinv_X

array([[ 3.10955194e+00, -2.77280100e+00, -7.21155221e-03,
        -5.18430128e-03, -5.51208106e-02, -1.23548021e-03,
         6.65624171e-03],
       [-2.77280100e+00,  3.10955194e+00, -7.21155221e-03,
        -5.18430128e-03, -5.51208106e-02, -1.23548021e-03,
         6.65624171e-03],
       [-7.21155221e-03, -7.21155221e-03,  3.71835782e-03,
        -1.57619450e-04,  4.56104176e-03,  1.49712910e-04,
        -1.61576960e-03],
       [-5.18430128e-03, -5.18430128e-03, -1.57619450e-04,
         2.59861018e-04,  1.16051135e-03, -5.07276503e-05,
         1.88500927e-04],
       [-5.51208106e-02, -5.51208106e-02,  4.56104176e-03,
         1.16051135e-03,  1.81238711e-01,  1.09090690e-04,
        -1.28527139e-03],
       [-1.23548021e-03, -1.23548021e-03,  1.49712910e-04,
        -5.07276503e-05,  1.09090690e-04,  1.45565569e-04,
        -4.48401970e-04],
       [ 6.65624171e-03,  6.65624171e-03, -1.61576960e-03,
         1.88500927e-04, -1.28527139e-03, -4.48401970e-04,
         5.4570421

In [111]:
# computing the weights
weight_reg = np.dot(np.dot(X_tran_reg_pinv_X, X_train.T), y_train)
weight_reg

array([-3.57152464, -3.57152464,  3.24302274,  0.1571384 , 11.74050198,
        0.38023007, -1.57443304])

In [112]:
y_pred_train_reg = np.dot(X_train, weight_reg)
y_pred_train_reg

array([45.80796927, 14.54418331, 17.16288353, 31.84466659,  8.51378572,
       30.17918901, 22.42595051, 23.81753544, 23.8175737 , 42.85795996,
       30.53552725, 19.96313369,  2.30989592, 18.94246548, 24.40125817,
       22.26944028, 22.23957368, 24.55493279, 23.17000144, 33.60310345,
       19.26252338, 45.9592231 , 25.57086236, 28.25835487, 28.08454158,
       32.72862332, 27.58368188, 22.49067632, 32.7304732 , 28.23657954,
       19.82310111, 25.0437932 , 27.85092551, 31.58908412, 33.10644728,
       40.51589299, 32.21421409, 32.97218107, 35.8180879 , 57.80686318])

**Regularized Newton Method - Testing Computation**

In [113]:
# computing the pseudo-inverse of (X'X+lambda*I)^-1)
X_tran_reg_pinv_X1 = np.linalg.pinv(np.dot(X_test.T, X_test) + lambda_reg * np.eye(X_test.shape[1]))
X_tran_reg_pinv_X1

array([[ 5.38048147e+00, -5.01871476e-01, -1.73705950e-01,
        -9.66703711e-02,  2.81002483e-01, -8.68499136e-03,
        -6.00759184e-02],
       [-5.01871476e-01,  5.38048147e+00, -1.73705950e-01,
        -9.66703711e-02,  2.81002483e-01, -8.68499136e-03,
        -6.00759184e-02],
       [-1.73705950e-01, -1.73705950e-01,  2.77180790e-02,
         6.94469159e-03, -7.08120541e-02, -1.57184609e-03,
         7.77126904e-03],
       [-9.66703711e-02, -9.66703711e-02,  6.94469159e-03,
         4.39475501e-03, -1.91834128e-02, -5.92919083e-04,
         1.79633785e-03],
       [ 2.81002483e-01,  2.81002483e-01, -7.08120541e-02,
        -1.91834128e-02,  9.26927863e-01,  1.75743788e-02,
        -6.43490606e-02],
       [-8.68499136e-03, -8.68499136e-03, -1.57184609e-03,
        -5.92919083e-04,  1.75743788e-02,  2.23956517e-03,
        -6.20369010e-04],
       [-6.00759184e-02, -6.00759184e-02,  7.77126904e-03,
         1.79633785e-03, -6.43490606e-02, -6.20369010e-04,
         3.1787249

In [114]:
# computing the weights
weight_reg_test = np.dot(np.dot(X_tran_reg_pinv_X1, X_test.T), y_test)
weight_reg_test

array([-1.20859797, -1.20859797,  3.18255534,  0.07293882, 10.52600926,
        0.34775951, -1.5305359 ])

In [115]:
y_pred_test_reg = np.dot(X_test, weight_reg_test)
y_pred_test_reg

array([28.32886843, 10.88626556, 21.03645295,  5.65401242, 26.88171   ,
       -0.67848471, 25.62608152, 33.47055549])

**Computing the train and test predictions for Regularized Newton Method**

In [116]:
SSR_train_reg = np.sum((y_train - y_pred_train_reg)**2)
MSR_train_reg = SSR_train_reg / (len(y_train))
RMSE_train_reg = np.sqrt(MSR_train_reg)

In [117]:
print("Training SSR_Reg:", SSR_train_reg)

Training SSR_Reg: 4.241977175181848


In [118]:
print("Training MSR_Reg:", MSR_train_reg)

Training MSR_Reg: 0.1060494293795462


In [119]:
print("Training RMSE_Reg:", RMSE_train_reg)

Training RMSE_Reg: 0.32565231364070824


In [120]:
SSR_test_reg = np.sum((y_test - y_pred_test_reg) ** 2)
MSR_test_reg = SSR_test_reg / (len(y_test))
RMSE_test_reg = np.sqrt(MSR_test_reg)

In [121]:
print("Testing SSR_Reg:", SSR_test_reg)

Testing SSR_Reg: 4.456060534201329


In [122]:
print("Testing MSR_Reg:", MSR_test_reg)

Testing MSR_Reg: 0.5570075667751662


In [123]:
print("Testing RMSE_Reg:", RMSE_test_reg)

Testing RMSE_Reg: 0.7463293956257961


### MSR on train, MSR on test, R-squared on train and R-squared on test for the following:

In [124]:
# defining r-squared function
def r_squared(y_actual, y_pred):
    ss_total = np.sum((y_actual - np.mean(y_actual)) ** 2)
    ss_res = np.sum((y_actual - y_pred) ** 2)
    return 1 - (ss_res / ss_total)

In [125]:
# creating a function for the computation of MSR and R-Squared
def computations(train_rows, test_rows, lambda_val):
    
    # extracting X and y values for training
    X_train = np_df.iloc[train_rows[0]:train_rows[1], :6].values
    y_train = np_df.iloc[train_rows[0]:train_rows[1], :6].values
    X_train = np.hstack((np.ones((X_train.shape[0], 1)), X_train))
    
    # extracting X and y values for test
    X_test = np_df.iloc[test_rows[0]:test_rows[1], :6].values
    y_test = np_df.iloc[test_rows[0]:test_rows[1], :6].values
    X_test = np.hstack((np.ones((X_test.shape[0], 1)), X_test))
    
    # regularizing Newton method
    # training computation
    X_reg_pinv_train = np.linalg.pinv(np.dot(X_train.T, X_train) + lambda_val * np.eye(X_train.shape[1])) 
    weight_reg_train = np.dot(np.dot(X_reg_pinv_train, X_train.T), y_train)
    
    # testing computation
    X_reg_pinv_test = np.linalg.pinv(np.dot(X_test.T, X_test) + lambda_val * np.eye(X_test.shape[1])) 
    weight_reg_test = np.dot(np.dot(X_reg_pinv_test, X_test.T), y_test)
    
    # generating y values from the weights
    y_pred_train_reg = np.dot(X_train, weight_reg_train)
    y_pred_test_reg = np.dot(X_test, weight_reg_test)
    
    # computing SSR and MSR for training
    SSR_train_reg = np.sum((y_train - y_pred_train_reg) ** 2)
    MSR_train_reg = SSR_train_reg / (len(y_train))
    
    # computing SSR and MSR for testing
    SSR_test_reg = np.sum((y_test - y_pred_test_reg) ** 2)
    MSR_test_reg = SSR_test_reg / (len(y_test))
    
    # computing R-squared values
    R2_train_reg = r_squared(y_train, y_pred_train_reg)
    R2_test_reg = r_squared(y_test, y_pred_test_reg)
    
    return MSR_train_reg, MSR_test_reg, R2_train_reg, R2_test_reg

**1. Use only rows 2 to 41 for training and rows 42 to 51 for testing and lambda as 0.83**

**2. Use only rows 2 to 26 for training and rows 27 to 51 for testing and lambda as 0.17**

**3. Use only rows 2 to 26 for training and rows 27 to 51 for testing and lambda as 0.83**

**4. Use only rows 2 to 11 for training and rows 12 to 51 for testing and lambda as 0.17**

**5. Use only rows 2 to 11 for training and rows 12 to 51 for testing and lambda as 0.83**

In [126]:
# computation for above examples

results = []

scenarios = [
    ([1, 41], [41, 51], 0.83),
    ([1, 26], [26, 51], 0.17),
    ([1, 26], [26, 51], 0.83),
    ([1, 11], [11, 51], 0.17),
    ([1, 11], [11, 51], 0.83),
]

for scenario in scenarios:
    results.append(computations(*scenario))

# Print results
for i, result in enumerate(results):
    print(f"\nCase {i + 1}: \nMSR Train: {result[0]}, \nMSR Test: {result[1]}, \nR-squared Train: {result[2]}, \nR-squared Test: {result[3]}")


Case 1: 
MSR Train: 0.00428586969491983, 
MSR Test: 0.02777351095522945, 
R-squared Train: 0.9999981579049236, 
R-squared Test: 0.9999826741680861

Case 2: 
MSR Train: 0.0007181400881850452, 
MSR Test: 0.0007063155994490736, 
R-squared Train: 0.9999996183026731, 
R-squared Test: 0.9999997188042986

Case 3: 
MSR Train: 0.009844520890579647, 
MSR Test: 0.009789692077646612, 
R-squared Train: 0.9999947675566785, 
R-squared Test: 0.9999961025647283

Case 4: 
MSR Train: 0.0014206402809189944, 
MSR Test: 0.00025047051091760253, 
R-squared Train: 0.9999992385432711, 
R-squared Test: 0.9999998901148855

Case 5: 
MSR Train: 0.013155322708161258, 
MSR Test: 0.0041967011103176514, 
R-squared Train: 0.9999929488068645, 
R-squared Test: 0.9999981588452056
