In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3])

In [3]:
array

array([1, 2, 3])

In [4]:
array * 3

array([3, 6, 9])

In [7]:
array

array([1, 2, 3])

## 02_01 Array types and conversions between types

In [8]:
integers = np.array([10,20,20,40,50])

In [9]:
integers[0]

10

In [10]:
integers[0] = 20

In [11]:
integers

array([20, 20, 20, 40, 50])

In [12]:
integers[0] = 21.7
integers

array([21, 20, 20, 40, 50])

In [13]:
# Checking the data type
integers.dtype

dtype('int32')

In [14]:
smallerIntegers = np.array(integers, dtype = np.int8)
smallerIntegers

array([21, 20, 20, 40, 50], dtype=int8)

In [15]:
integers.nbytes

20

In [16]:
smallerIntegers.nbytes

5

## Multidimensional Arrays

In [17]:
nums = np.array([[1,2,3,4,5],[6,7,8,9,10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
nums[0,0]

1

In [21]:
nums[1,4]

10

In [22]:
nums.ndim

2

In [29]:
# An array of two, two-dimensional array is a three dimensional array
multi_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
multi_arr.ndim

3

In [31]:
integers.ndim

1

In [32]:
multi_arr[1,1,2]

12

In [33]:
multi_arr[1,0,2]

9

In [34]:
three_d_arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[7,8,9],[10,11,12],[4,5,6]],[[1,2,3],[4,5,6],[10,11,12]]])
three_d_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 11, 12]]])

In [35]:
three_d_arr.ndim

3

In [36]:
three_d_arr[1,1,2]

12

## Creating arrays from Lists and other Python Structures

In [41]:
first_list = [i for i in range(1,11)]

In [42]:
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [44]:
first_array = np.array(first_list)
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Intrinsic NumPy Array Creation

In [46]:
# "arange" works like a range in python
int_arr = np.arange(1,10)
int_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
# "arange" with start, stop and step
int_sec_arr = np.arange(100,131,5)
int_sec_arr

array([100, 105, 110, 115, 120, 125, 130])

In [50]:
# "linspace" works with floats and can create arrays according to the number specified as the step value
# The array has equal spacing
float_arr = np.linspace(10,15)
float_arr

array([10.        , 10.10204082, 10.20408163, 10.30612245, 10.40816327,
       10.51020408, 10.6122449 , 10.71428571, 10.81632653, 10.91836735,
       11.02040816, 11.12244898, 11.2244898 , 11.32653061, 11.42857143,
       11.53061224, 11.63265306, 11.73469388, 11.83673469, 11.93877551,
       12.04081633, 12.14285714, 12.24489796, 12.34693878, 12.44897959,
       12.55102041, 12.65306122, 12.75510204, 12.85714286, 12.95918367,
       13.06122449, 13.16326531, 13.26530612, 13.36734694, 13.46938776,
       13.57142857, 13.67346939, 13.7755102 , 13.87755102, 13.97959184,
       14.08163265, 14.18367347, 14.28571429, 14.3877551 , 14.48979592,
       14.59183673, 14.69387755, 14.79591837, 14.89795918, 15.        ])

In [51]:
sec_float_arr = np.linspace(10,15,25)
sec_float_arr

array([10.        , 10.20833333, 10.41666667, 10.625     , 10.83333333,
       11.04166667, 11.25      , 11.45833333, 11.66666667, 11.875     ,
       12.08333333, 12.29166667, 12.5       , 12.70833333, 12.91666667,
       13.125     , 13.33333333, 13.54166667, 13.75      , 13.95833333,
       14.16666667, 14.375     , 14.58333333, 14.79166667, 15.        ])

In [52]:
# Creating Random Arrays
first_rand_arr = np.random.rand(10)
first_rand_arr

array([0.26256294, 0.38148174, 0.2798168 , 0.12547607, 0.09624046,
       0.51310049, 0.19536698, 0.11816418, 0.07662095, 0.53278852])

In [55]:
# Creating two or three dimensional arrays of random numbers
sec_rand_arr = np.random.rand(4,4,4)
sec_rand_arr

array([[[0.94097278, 0.20888435, 0.77958928, 0.33271198],
        [0.50149554, 0.20590888, 0.11887155, 0.08143128],
        [0.84475332, 0.79218128, 0.74640067, 0.61687972],
        [0.29370379, 0.07947026, 0.21623524, 0.62983949]],

       [[0.60377749, 0.41575498, 0.26096171, 0.74229926],
        [0.812862  , 0.78919442, 0.55621271, 0.5672895 ],
        [0.60917894, 0.82586709, 0.14535487, 0.11685883],
        [0.46787205, 0.60584765, 0.98971328, 0.17868419]],

       [[0.01864741, 0.35002925, 0.45113947, 0.67878707],
        [0.81713207, 0.00478134, 0.69825042, 0.81035067],
        [0.05579171, 0.45012461, 0.47710846, 0.95841655],
        [0.64628696, 0.10721023, 0.4191703 , 0.39152536]],

       [[0.79340946, 0.86635134, 0.12115699, 0.49192259],
        [0.83535731, 0.25440552, 0.8025375 , 0.31673   ],
        [0.56141076, 0.54898556, 0.39627682, 0.40978385],
        [0.81242439, 0.36408526, 0.43408155, 0.73798267]]])

In [54]:
sec_rand_arr.ndim

3

In [57]:
# Creating two or three dimensional arrays of random numbers
third_rand_arr = np.random.rand(4,4,4,4)
third_rand_arr

array([[[[0.71266182, 0.30010589, 0.33290477, 0.41477544],
         [0.2088168 , 0.89423626, 0.71807867, 0.62725403],
         [0.18139793, 0.21935556, 0.20940519, 0.5253739 ],
         [0.59732918, 0.85962895, 0.70494521, 0.37269953]],

        [[0.1903839 , 0.67598831, 0.68856983, 0.56927425],
         [0.48286552, 0.48207108, 0.52190037, 0.89890792],
         [0.43289443, 0.23173085, 0.44708407, 0.92049129],
         [0.82871042, 0.30324581, 0.56983626, 0.88553242]],

        [[0.07081599, 0.39677202, 0.77155616, 0.85397142],
         [0.56389999, 0.90948245, 0.57156825, 0.23756049],
         [0.14747711, 0.41749814, 0.64612956, 0.70368895],
         [0.94090765, 0.88526266, 0.95659569, 0.70067637]],

        [[0.21949762, 0.95280912, 0.64247216, 0.94801212],
         [0.66830797, 0.09497589, 0.24011574, 0.59534269],
         [0.7255734 , 0.70681234, 0.91301492, 0.79481186],
         [0.40800018, 0.69648255, 0.77424939, 0.99497919]]],


       [[[0.66291599, 0.76548786, 0.23655273, 

In [58]:
three_d_arr.ndim

3

## Creating arrays filled with constant values

In [59]:
z_arr = np.zeros(5) # creating an array with five zeros
z_arr

array([0., 0., 0., 0., 0.])

In [60]:
# Creating zeros arrays specifying the rows and columns
z_arr_rows_cols = np.zeros((4,5))
z_arr_rows_cols

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
ones_arr = np.ones(5) # creating an array with five ones (same as zeros)
ones_arr

array([1., 1., 1., 1., 1.])

In [62]:
ones_arr_rows_cols = np.ones((4,5), dtype=int)
ones_arr_rows_cols

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [63]:
# Using the fill function
fill_arr = np.empty(10, dtype=int) # creating an empty array with 10 spaces
fill_arr.fill(12) # filling the empty spaces with "12"
fill_arr

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [64]:
# Using the full function
full_arr = np.full(5, 10) # creates an array of 5 elements of 10's
full_arr

array([10, 10, 10, 10, 10])

In [65]:
full_rc_arr = np.full((4, 4), 8, dtype=int)
full_rc_arr

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [66]:
# Shape
full_rc_arr.shape


(4, 4)

In [67]:
# Size
np.size(full_rc_arr)

16